-- NOTE: put monkey-patched lua plugins here
--
-- For monkey-patching lua plugins, put lua files in this directory with content like:
--
-- ```lua
-- return {
--    "some/lua-plugin/that-needs-monkey-patch.nvim",
--    init = function()
--      -- TODO: do some monkey-patching here
--    end,
-- }
-- ```
return {}
