# .config/homebrew/Brewfile
#
# Usage: 
#
# $ brew tap Homebrew/bundle
# $ brew bundle --file=$XDG_CONFIG_HOME/homebrew/Brewfile
# 
# last update: 2023.07.20.

cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

######## formulas

# libraries
brew 'coreutils'

# utilities
brew 'ffmpeg'
brew 'gnu-sed'
brew 'htop'
brew 'lnav'
brew 'm-cli'
brew 'mas'	# for Mac App Store
brew 'mosh', args: ['HEAD']
brew 'ngrep'
brew 'neovim', args: ['HEAD']
brew 'pstree'
brew 'reattach-to-user-namespace'	# for using `pbcopy`, `pbpaste`, or `mas` in tmux
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zsh-syntax-highlighting'

# for dart/flutter
tap 'dart-lang/dart'
brew 'dart'

# other development tools
brew 'curl'
brew 'git'
brew 'git-flow'
brew 'gnupg'
brew 'jq'
brew 'mkcert'
tap 'tinygo-org/tools'
brew 'tinygo'
#brew 'wireshark'
#brew 'wrk'


######## casks

# utilities
cask 'dropbox'
cask 'google-chrome'
cask 'visual-studio-code'
cask 'kitty'

