# ~/.config/starship.toml
#
# https://starship.rs/config/
#
# (with asdf)
# $ asdf plugin add rust
# $ asdf install rust
# $ cargo install starship --locked
# $ asdf reshim
#
# (with brew)
# $ brew install starship
#
# created on : 2024.01.29.
# last update: 2024.09.27.

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$c\
$cmake\
$elixir\
$fennel\
$golang\
$java\
$kotlin\
$lua\
$nim\
$nodejs\
$python\
$ruby\
$rust\
$swift\
$zig\
$cmd_duration\
$status\
$container\
$character
\\$ """

[username]
style_user = 'blue'

[hostname]
style = 'bright-red'

[directory]
style = 'dimmed green'

[git_branch]
style = 'cyan'

[git_status]
style = 'red'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

[status]
disabled = false

